permalink: /:year/:month/:day/:title.html
markdown: kramdown
rouge: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: Lnek
  email: wsk2582458@gmail.com
  link: http://lnek.wang
  #weibo: http://weibo.com/lnekwang
  github: http://github.com/lnek

# 站点信息
title: Code & Poetry
description: Sleep & Eat
url: http://lnek.wang
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar:  ./assets/img/avatar.png
favicon: ./assets/img/avatar.png
# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# google analytics 设置
ga:
  id: UA-63929964-1
  url: lnek.wang
  # url: lnek.github.io

# disqus 设置
disqus:
  shortname: Lnek

theme: jekyll-theme-slate